//! Drift checks against a fixture FFI crate: the committed header and C#
//! file are what the generators render, and a stale, missing or CRLF copy
//! is reported, or rewritten when blessing.

use std::path::{Path, PathBuf};

use abi_drift::{cbindgen_header, csbindgen_file, Drift, Error, Outcome};

fn fixture() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/ffi")
}

fn header() -> String {
    cbindgen_header(fixture(), "cbindgen.toml", "src/lib.rs").expect("cbindgen renders")
}

fn csharp() -> String {
    let scratch = tempfile::tempdir().expect("scratch");
    let builder = csbindgen::Builder::new()
        .input_extern_file(fixture().join("src/lib.rs"))
        .csharp_dll_name("ffi")
        .csharp_namespace("Fixture.Native")
        .csharp_class_name("NativeMethods")
        .csharp_file_header("// Generated by csbindgen from tests/fixtures/ffi/src. Do not edit.");
    csbindgen_file(builder, scratch.path().join("NativeMethods.g.cs")).expect("csbindgen renders")
}

/// A checker over a scratch copy holding `committed` at `include/ffi.h`.
fn scratch_with(committed: Option<&str>) -> (tempfile::TempDir, Drift) {
    let dir = tempfile::tempdir().expect("dir");
    if let Some(text) = committed {
        std::fs::create_dir_all(dir.path().join("include")).expect("mkdir");
        std::fs::write(dir.path().join("include/ffi.h"), text).expect("write");
    }
    let drift = Drift::new(dir.path()).regenerate_with("just bindings");
    (dir, drift)
}

#[test]
fn the_committed_header_is_what_cbindgen_generates() {
    let drift = Drift::new(fixture()).bless_from_env("ABI_DRIFT_BLESS");
    let outcome = drift.check("include/ffi.h", &header()).expect("fresh");
    assert!(matches!(outcome, Outcome::Fresh | Outcome::Blessed));
    assert!(header().contains("int32_t ffi_add(int32_t a, int32_t b);"));
}

#[test]
fn the_committed_csharp_is_what_csbindgen_generates() {
    let drift = Drift::new(fixture()).bless_from_env("ABI_DRIFT_BLESS");
    let outcome = drift
        .check("bindings/NativeMethods.g.cs", &csharp())
        .expect("fresh");
    assert!(matches!(outcome, Outcome::Fresh | Outcome::Blessed));
    assert!(csharp().contains("ffi_origin"));
}

#[test]
fn a_stale_copy_shows_a_unified_diff_and_the_command() {
    let rendered = header();
    let stale = rendered.replace("int32_t b", "int64_t b");
    let (_dir, drift) = scratch_with(Some(&stale));
    let err = drift.check("include/ffi.h", &rendered).expect_err("stale");
    let Error::Stale { path, hint, diff } = &err else {
        panic!("not stale: {err}");
    };
    assert_eq!(path, "include/ffi.h");
    assert_eq!(hint, "just bindings");
    assert!(diff.contains("--- include/ffi.h (committed)"), "{diff}");
    assert!(
        diff.contains("-int32_t ffi_add(int32_t a, int64_t b);"),
        "{diff}"
    );
    assert!(
        diff.contains("+int32_t ffi_add(int32_t a, int32_t b);"),
        "{diff}"
    );
    // A failing test prints `Debug`, which carries the same readable diff.
    let debug = format!("{err:?}");
    assert!(
        debug.starts_with("include/ffi.h is stale: run `just bindings`"),
        "{debug}"
    );
    assert!(debug.contains("+int32_t ffi_add"), "{debug}");
}

#[test]
fn blessing_rewrites_the_copy_and_then_it_is_fresh() {
    let rendered = header();
    let (dir, drift) = scratch_with(Some("old\n"));
    assert_eq!(
        drift
            .clone()
            .bless(true)
            .check("include/ffi.h", &rendered)
            .expect("bless"),
        Outcome::Blessed
    );
    assert_eq!(
        std::fs::read_to_string(dir.path().join("include/ffi.h")).expect("read"),
        rendered
    );
    assert_eq!(
        drift.check("include/ffi.h", &rendered).expect("fresh"),
        Outcome::Fresh
    );
}

#[test]
fn blessing_creates_a_missing_file_and_its_directory() {
    let (dir, drift) = scratch_with(None);
    let outcome = drift
        .bless(true)
        .check("bindings/csharp/N.g.cs", "x\n")
        .expect("bless");
    assert_eq!(outcome, Outcome::Blessed);
    assert!(dir.path().join("bindings/csharp/N.g.cs").is_file());
}

#[test]
fn a_missing_copy_is_stale_with_every_line_added() {
    let (_dir, drift) = scratch_with(None);
    let err = drift.check("include/ffi.h", "a\nb\n").expect_err("stale");
    let Error::Stale { diff, .. } = err else {
        panic!("not stale");
    };
    assert!(diff.contains("+a\n+b\n"), "{diff}");
}

#[test]
fn crlf_line_endings_do_not_count_as_drift() {
    let rendered = header();
    let (_dir, drift) = scratch_with(Some(&rendered.replace('\n', "\r\n")));
    assert_eq!(
        drift.check("include/ffi.h", &rendered).expect("fresh"),
        Outcome::Fresh
    );
}

#[test]
fn an_unset_bless_variable_compares_and_names_itself() {
    let (_dir, drift) = scratch_with(Some("old\n"));
    let err = drift
        .bless_from_env("ABI_DRIFT_TEST_VARIABLE_NEVER_SET")
        .check("include/ffi.h", "new\n")
        .expect_err("compares, does not bless");
    assert!(err
        .to_string()
        .contains("run `ABI_DRIFT_TEST_VARIABLE_NEVER_SET=1 cargo test`"));
}

#[test]
fn a_broken_config_is_a_generate_error() {
    let err = cbindgen_header(fixture(), "no-such.toml", "src/lib.rs").expect_err("no config");
    assert!(matches!(err, Error::Generate(_)), "{err}");
}
