// Generated by csbindgen from tests/fixtures/ffi/src. Do not edit.
// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Fixture.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "ffi";





        /// <summary>
        ///  Adds two numbers.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ffi_add", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int ffi_add(int a, int b);

        /// <summary>
        ///  The origin.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "ffi_origin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern FfiPoint ffi_origin();


    }

    /// <summary>
    ///  A point in the fixture's ABI.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct FfiPoint
    {
        public int x;
        public int y;
    }



}
