#!/usr/bin/env python3
"""Writes src/chains.rs: transient chains of depth 10, 20 and 50, wired by
injecta and by hand. Run from this directory, then `cargo fmt`."""

DEPTHS = (10, 20, 50)


def chain(d):
    out = [f"/// Chain of depth {d}.", f"pub mod chain{d} {{", "    use injecta::{Injectable, Resolve};", ""]
    out += ["    /// The leaf, passed to the container as an instance.", "    #[derive(Clone)]",
            "    pub struct L0 {", "        /// Value summed by `sum`.", "        pub tag: u64,", "    }"]
    for n in range(1, d + 1):
        out += [f"    /// Level {n}.", "    #[derive(Injectable)]", f"    pub struct L{n} {{",
                f"        prev: L{n - 1},", f"        #[inject(value = {n})]", "        tag: u64,", "    }"]
    expr, path = "self.tag", "self"
    for _ in range(d, 0, -1):
        path += ".prev"
        expr += f" + {path}.tag"
    out += ["", f"    impl L{d} {{", "        /// Sum of every level's tag, so the chain cannot be optimized away.",
            "        #[must_use]", "        pub fn sum(&self) -> u64 {", f"            {expr}", "        }", "    }", ""]
    out += ["    injecta::container! {", "        /// Every level as a transient.", "        pub struct Chain {",
            "            instance L0,"]
    out += [f"            transient L{n}," for n in range(1, d + 1)]
    out += ["        }", "    }", ""]
    out += ["    /// Resolves the top of the chain through injecta.", "    #[must_use]",
            "    pub fn injecta(c: &Chain) -> u64 {", f"        c.resolve::<L{d}>().sum()", "    }", ""]
    build = "leaf.clone()"
    for n in range(1, d + 1):
        build = f"L{n} {{ prev: {build}, tag: {n} }}"
    out += ["    /// The same chain built by hand.", "    #[must_use]", "    pub fn by_hand(leaf: &L0) -> u64 {",
            f"        {build}.sum()", "    }", "}", ""]
    return out


lines = ["//! Generated by `gen_chains.py`: transient dependency chains of depth 10, 20 and 50,",
         "//! each wired by injecta and by hand. `L0` is an instance; `L<n>` holds `L<n-1>`.", ""]
for depth in DEPTHS:
    lines += chain(depth)
with open("src/chains.rs", "w") as f:
    f.write("\n".join(lines))
