//! The Anthropic Messages API backend: request translation, the SSE stream
//! parser and a streaming client.
//!
//! The wire types are generated by `build.rs` with typify from the vendored
//! spec in `schema/`; they stay private, the other modules are their only
//! consumers.

/// Wire types generated from the vendored OpenAPI spec — internal to this
/// crate.
// Temporary: nothing consumes the types until `request` and `stream` land.
#[allow(unused_imports)]
mod wire;
