//! The Anthropic Messages API backend: the client handle, its headers and
//! its credential lookup. The body translation lives next door in
//! [`request`] so it can be snapshot-tested with no key and no socket; the
//! SSE → `ProviderEvent` state machine lives in [`stream`] for the same
//! reason (fixtures, no socket).
//!
//! Kept apart from the OpenAI backends because the fields that decide cost
//! here — `cache_control` placement, `output_config.effort`, adaptive
//! `thinking`, `fallbacks` — have no counterpart there.
//!
//! The wire types are generated by `build.rs` with typify from the vendored
//! spec in `schema/`; they stay private, `request` and `stream` are their only
//! consumers.

pub mod request;
pub mod stream;
/// Wire types generated from the vendored OpenAPI spec — internal to this
/// module; `request` and `stream` are the only consumers.
mod wire;

use async_trait::async_trait;
use futures::StreamExt;
use llm_wire::{Caps, Provider, ProviderError, ProviderEvent, ProviderId, Request, Usage};
use reqwest::header::{HeaderMap, HeaderValue};
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;
// Imported at the crate root so the `crate::http`/`crate::retry`/`crate::sse`
// paths this wire used inside cox resolve unchanged.
use llm_http::{http, retry, sse};

/// The API version this wire pins; Anthropic requires it on every request.
pub const ANTHROPIC_VERSION: &str = "2023-06-01";

/// The beta that gates the scalar `fallbacks: "default"` form. The array
/// form uses `server-side-fallback-2026-06-01` instead and pairing either
/// header with the other form is a 400, so the two are never both sent.
pub const FALLBACKS_BETA: &str = "server-side-fallback-2026-07-01";

/// How long a cache entry written by a `cache_control` breakpoint lives.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CacheTtl {
    /// The API default.
    #[default]
    FiveMinutes,
    /// Longer TTL for bursty sessions; writes cost more.
    OneHour,
}

impl CacheTtl {
    /// The wire value for `cache_control.ttl`.
    pub fn as_str(self) -> &'static str {
        match self {
            CacheTtl::FiveMinutes => "5m",
            CacheTtl::OneHour => "1h",
        }
    }
}

/// The connection settings every HTTP wire reads from its config section.
///
/// Mirrors cox's `cox_protocol::config::Transport`, which is not part of
/// `llm-wire`; a caller copies its four fields across.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Transport {
    /// Base URL of the API, e.g. `https://api.anthropic.com`.
    pub base_url: String,
    /// Name of the environment variable holding the API key.
    pub api_key_env: String,
    /// Idle-read timeout in seconds, between stream chunks.
    pub timeout_s: u32,
    /// Max retries for retryable errors.
    pub max_retries: u32,
}

/// A configured Anthropic Messages client.
///
/// Fields are public because the caller builds one straight from its config
/// section; there is no behaviour worth hiding behind accessors.
pub struct AnthropicProvider {
    /// The base URL, without a trailing slash.
    pub base_url: String,
    /// The resolved credential (see [`crate::http::resolve_key`]), or
    /// `None` for a keyless client (LM Studio's `/v1/messages` without
    /// "Require Authentication" needs no `x-api-key` at all — the real
    /// Anthropic API always fails `Auth` before a `None` reaches here, since
    /// [`Self::new`] requires a resolved key).
    pub api_key: Option<String>,
    /// Sent as `anthropic-workspace-id` (see [`resolve_workspace_id`]).
    pub workspace_id: Option<String>,
    /// TTL written into every `cache_control` block.
    pub ttl: CacheTtl,
    /// Whether to send `fallbacks: "default"` and its beta header.
    pub fallbacks: bool,
    /// The shared connection pool.
    pub http: reqwest::Client,
    /// Backoff for transient failures before the first byte.
    pub retry: crate::retry::Policy,
    /// `Caps.max_context`: resolved once by the caller from its model
    /// catalog for the configured model, not looked up here —
    /// `capabilities()` carries no per-request model, so the value is fixed
    /// at construction. A caller whose catalog has no row for the model uses
    /// 200 000.
    pub max_context: u32,
}

impl AnthropicProvider {
    /// Builds a provider from a [`Transport`] with an already-resolved
    /// credential, or `None` for a keyless client (LM Studio's `/v1/messages`
    /// without "Require Authentication"). Prefer [`Self::new`] at startup for
    /// the real Anthropic API, which always needs a key; this stays for tests
    /// and any caller that already resolved (or deliberately skipped) one, so
    /// a test can inject the lookup instead of ever reaching the real
    /// keyring.
    pub fn with_key(
        transport: &Transport,
        api_key: Option<String>,
        ttl: CacheTtl,
        fallbacks: bool,
        max_context: u32,
    ) -> Result<Self, ProviderError> {
        Ok(Self {
            base_url: transport.base_url.trim_end_matches('/').to_string(),
            api_key,
            workspace_id: resolve_workspace_id(),
            ttl,
            fallbacks,
            http: crate::http::client_with_timeout(transport.timeout_s)?,
            retry: crate::retry::Policy {
                max_retries: transport.max_retries,
                ..Default::default()
            },
            max_context,
        })
    }

    /// Builds a provider from a [`Transport`] plus its own section-specific
    /// knobs (cache TTL, whether to send `fallbacks`, the catalog-resolved
    /// `max_context`). Resolves the credential from `transport.api_key_env`
    /// or the keyring entry `keyring_service`/`anthropic`; the environment
    /// variable `keyring_switch_env` turns the keyring off (see
    /// [`crate::http::resolve_key`]). Fails with [`ProviderError::Auth`]
    /// rather than panicking when neither has a key. `transport.timeout_s` is
    /// the idle-read timeout between stream chunks, not a whole-call cap: a
    /// long answer streams for minutes without ever being idle.
    pub fn new(
        transport: &Transport,
        keyring_service: &str,
        keyring_switch_env: &str,
        ttl: CacheTtl,
        fallbacks: bool,
        max_context: u32,
    ) -> Result<Self, ProviderError> {
        let api_key = crate::http::resolve_key(
            &transport.api_key_env,
            keyring_service,
            "anthropic",
            keyring_switch_env,
        )?;
        Self::with_key(transport, Some(api_key), ttl, fallbacks, max_context)
    }

    /// The headers every call carries. `anthropic-beta` is assembled from
    /// the features actually enabled, so a request never claims a beta it
    /// does not use (some betas 400 when paired with the wrong body shape).
    pub fn headers(&self) -> Result<HeaderMap, ProviderError> {
        let mut h = HeaderMap::new();
        h.insert("content-type", HeaderValue::from_static("application/json"));
        h.insert(
            "anthropic-version",
            HeaderValue::from_static(ANTHROPIC_VERSION),
        );
        // An api key with non-ASCII bytes is a misconfigured credential, not
        // a transport failure: report it as an auth problem. `None` (LM
        // Studio without "Require Authentication") sends no header at all,
        // rather than an empty one.
        if let Some(key) = &self.api_key {
            h.insert("x-api-key", crate::http::api_key(key)?);
        }
        if let Some(id) = &self.workspace_id {
            // Same reasoning as the key: a bad id is a credential problem.
            let value = HeaderValue::from_str(id).map_err(|_| ProviderError::Auth)?;
            h.insert("anthropic-workspace-id", value);
        }

        let betas = self.betas();
        if !betas.is_empty() {
            let value = HeaderValue::from_str(&betas.join(",")).map_err(|_| {
                ProviderError::Unsupported {
                    feature: "anthropic-beta".into(),
                }
            })?;
            h.insert("anthropic-beta", value);
        }
        Ok(h)
    }

    /// The `anthropic-beta` values implied by the enabled features.
    pub fn betas(&self) -> Vec<&'static str> {
        let mut v = Vec::new();
        if self.fallbacks {
            v.push(FALLBACKS_BETA);
        }
        v
    }

    /// The config [`request::build_body`] needs from this provider.
    pub fn build_cfg<'a>(
        &self,
        thinking_model: Option<&'a llm_wire::ModelId>,
    ) -> request::BuildCfg<'a> {
        request::BuildCfg {
            ttl: self.ttl,
            fallbacks: self.fallbacks,
            thinking_model,
        }
    }
}

/// `ANTHROPIC_WORKSPACE_ID`, blank meaning unset. A key that is not scoped
/// to a workspace gets a 400 on every call unless this header names one.
/// Not a secret, so there is no keyring fallback.
pub fn resolve_workspace_id() -> Option<String> {
    workspace_id_from(|name| std::env::var(name).ok())
}

/// [`resolve_workspace_id`] with the environment injected, so a test needs
/// no `set_var` (this crate forbids `unsafe`).
fn workspace_id_from(read_env: impl Fn(&str) -> Option<String>) -> Option<String> {
    read_env("ANTHROPIC_WORKSPACE_ID")
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

#[async_trait]
impl Provider for AnthropicProvider {
    fn id(&self) -> ProviderId {
        ProviderId::Anthropic
    }

    fn capabilities(&self) -> Caps {
        Caps {
            cache: true,
            thinking: true,
            server_tools: true,
            count_tokens: true,
            // Resolved by the caller from its catalog; see
            // `Self::max_context`'s doc.
            max_context: self.max_context,
        }
    }

    /// Every Messages model takes base64 image blocks.
    fn accepts_images(&self, _model: &str) -> bool {
        true
    }

    async fn stream(
        &self,
        req: Request,
        sink: mpsc::Sender<ProviderEvent>,
        cancel: CancellationToken,
    ) -> Result<Usage, ProviderError> {
        crate::retry::stream_with_retry(self.retry, sink, cancel, |sink, cancel| {
            self.stream_once(&req, sink, cancel)
        })
        .await
    }

    async fn count_tokens(&self, _req: &Request) -> Result<u32, ProviderError> {
        // `POST {base_url}/v1/messages/count_tokens` with the same body;
        // out of scope for the streaming wire; cox lands it in its T1.8.
        Err(ProviderError::Unsupported {
            feature: "count_tokens lands in T1.8".into(),
        })
    }
}

impl AnthropicProvider {
    /// One HTTP attempt; `stream` wraps it in the retry policy.
    async fn stream_once(
        &self,
        req: &Request,
        sink: mpsc::Sender<ProviderEvent>,
        cancel: CancellationToken,
    ) -> Result<Usage, ProviderError> {
        let started = std::time::Instant::now();
        // No `ModelSwitched` signal reaches a `Provider`: `stream`'s
        // signature carries only the `Request`, so thinking-block replay
        // stays off here — see request.rs's `BuildCfg::thinking_model` doc.
        let body = request::build_body(req, self.build_cfg(None))?;

        let response = self
            .http
            .post(format!("{}/v1/messages", self.base_url))
            .headers(self.headers()?)
            .json(&body)
            .send()
            .await
            .map_err(|e| {
                if e.is_timeout() {
                    ProviderError::Timeout
                } else {
                    ProviderError::Network
                }
            })?;

        let status = response.status();
        if !status.is_success() {
            let retry_after = response
                .headers()
                .get(reqwest::header::RETRY_AFTER)
                .and_then(|v| v.to_str().ok())
                .and_then(|v| v.parse::<u64>().ok());
            let body_text = response.text().await.unwrap_or_default();
            return Err(http_error(status, &body_text, retry_after));
        }

        let mut frames = std::pin::pin!(crate::sse::sse_stream(response.bytes_stream()));
        let mut machine = stream::AnthropicStream::new();
        loop {
            let next = tokio::select! {
                biased;
                _ = cancel.cancelled() => return Err(ProviderError::Cancelled),
                frame = frames.next() => frame,
            };
            let Some(frame) = next else {
                break;
            };
            let (event, data) = frame.map_err(|_| ProviderError::Network)?;
            for provider_event in machine.feed(event.as_deref(), &data)? {
                // The receiving end (the agent loop) hung up: nothing left to
                // stream to, so unwind as a cancellation rather than
                // silently dropping the rest of the call.
                if sink.send(provider_event).await.is_err() {
                    return Err(ProviderError::Cancelled);
                }
            }
        }

        let mut usage = machine.usage();
        usage.latency_ms = started.elapsed().as_millis() as u64;
        Ok(usage)
    }
}

/// Maps a non-2xx `/v1/messages` response to a `ProviderError`. `retry_after`
/// comes from the `retry-after` header, read before the body is consumed. One
/// shared mapping lives in [`crate::http`]; this stays as the module's named
/// entry point for it.
fn http_error(status: reqwest::StatusCode, body: &str, retry_after: Option<u64>) -> ProviderError {
    crate::http::map_http_error(status, body, retry_after)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn provider(fallbacks: bool) -> AnthropicProvider {
        AnthropicProvider {
            base_url: "https://api.anthropic.com".into(),
            api_key: Some("sk-test".into()),
            workspace_id: None,
            ttl: CacheTtl::FiveMinutes,
            fallbacks,
            http: reqwest::Client::new(),
            retry: crate::retry::Policy {
                max_retries: 4,
                base: std::time::Duration::from_millis(1),
            },
            max_context: 200_000,
        }
    }

    fn one_tool_call_fixture() -> String {
        std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/one_tool_call.sse"),
        )
        .expect("fixture reads")
    }

    async fn drain_events(rx: &mut mpsc::Receiver<ProviderEvent>) -> Vec<ProviderEvent> {
        let mut out = Vec::new();
        while let Ok(event) = rx.try_recv() {
            out.push(event);
        }
        out
    }

    #[test]
    fn beta_header_only_lists_enabled_features() {
        assert!(provider(false).betas().is_empty());
        assert_eq!(provider(true).betas(), vec![FALLBACKS_BETA]);

        let h = provider(false).headers().expect("headers build");
        assert!(h.get("anthropic-beta").is_none());
        assert_eq!(
            h.get("anthropic-version").and_then(|v| v.to_str().ok()),
            Some(ANTHROPIC_VERSION)
        );

        let h = provider(true).headers().expect("headers build");
        assert_eq!(
            h.get("anthropic-beta").and_then(|v| v.to_str().ok()),
            Some(FALLBACKS_BETA)
        );
    }

    #[test]
    fn workspace_header_is_sent_only_when_configured() {
        let h = provider(false).headers().expect("headers build");
        assert!(h.get("anthropic-workspace-id").is_none());

        let mut p = provider(false);
        p.workspace_id = Some("wrkspc_01abc".into());
        let h = p.headers().expect("headers build");
        assert_eq!(
            h.get("anthropic-workspace-id")
                .and_then(|v| v.to_str().ok()),
            Some("wrkspc_01abc")
        );

        p.workspace_id = Some("bad\nid".into());
        assert!(matches!(p.headers(), Err(ProviderError::Auth)));
    }

    #[test]
    fn blank_workspace_env_means_unset() {
        assert_eq!(workspace_id_from(|_| Some("  ".into())), None);
        assert_eq!(workspace_id_from(|_| None), None);
        assert_eq!(
            workspace_id_from(|name| {
                assert_eq!(name, "ANTHROPIC_WORKSPACE_ID");
                Some(" wrkspc_01abc ".into())
            })
            .as_deref(),
            Some("wrkspc_01abc")
        );
    }

    #[test]
    fn missing_credential_is_auth_error_not_a_panic() {
        // Inject the lookup rather than calling `resolve_key`, whose
        // fallback is the real platform keyring. The env-over-keyring
        // precedence itself is proved in llm-http.
        assert!(matches!(
            crate::http::resolve_key_with("LLM_ANTHROPIC_TEST_MISSING", "anthropic", |_| None),
            Err(ProviderError::Auth)
        ));
    }

    /// `AnthropicProvider::new` reads whatever env var the transport names,
    /// not a hardcoded `ANTHROPIC_API_KEY` — a renamed section still resolves
    /// its key. `PATH` stands in for the renamed variable: it is always set,
    /// so the keyring is never consulted and the test needs no `set_var`.
    #[test]
    fn provider_new_honours_a_renamed_api_key_env() {
        let transport = Transport {
            base_url: "https://api.anthropic.com".to_string(),
            api_key_env: "PATH".to_string(),
            timeout_s: 30,
            max_retries: 1,
        };
        let p = AnthropicProvider::new(
            &transport,
            "llm-anthropic-test",
            "LLM_ANTHROPIC_TEST_KEYRING",
            CacheTtl::FiveMinutes,
            true,
            200_000,
        )
        .expect("builds with the renamed env var");
        assert_eq!(p.api_key, std::env::var("PATH").ok());
    }

    /// `capabilities().max_context` is whatever the caller resolved at
    /// construction, not a fixed literal — the provider-level half of the
    /// "1M-context model reports 1M" claim; the catalog lookup is the
    /// caller's.
    #[test]
    fn capabilities_max_context_is_whatever_was_resolved_at_construction() {
        let mut p = provider(false);
        p.max_context = 1_000_000;
        assert_eq!(p.capabilities().max_context, 1_000_000);
    }

    #[test]
    fn http_error_maps_known_statuses() {
        assert!(matches!(
            http_error(reqwest::StatusCode::UNAUTHORIZED, "{}", None),
            ProviderError::Auth
        ));
        assert!(matches!(
            http_error(reqwest::StatusCode::TOO_MANY_REQUESTS, "{}", Some(30)),
            ProviderError::RateLimited {
                retry_after: Some(30)
            }
        ));
        assert!(matches!(
            http_error(reqwest::StatusCode::SERVICE_UNAVAILABLE, "{}", None),
            ProviderError::Overloaded
        ));
        let body = r#"{"type":"error","error":{"type":"invalid_request_error","message":"prompt is too long: 250000 tokens > 200000 maximum"}}"#;
        assert_eq!(
            http_error(reqwest::StatusCode::BAD_REQUEST, body, None),
            ProviderError::ContextTooLong {
                max: 200_000,
                got: 250_000,
            }
        );
        let body = r#"{"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate"}}"#;
        assert_eq!(
            http_error(reqwest::StatusCode::BAD_REQUEST, body, None),
            ProviderError::BadRequest {
                message: "messages: roles must alternate".into(),
            }
        );
    }

    fn minimal_request() -> Request {
        use llm_wire::{Content, Effort, Job, Message, Role, Thinking, Tier};

        Request {
            tier: Tier::Code,
            job: Job::Main,
            model: llm_wire::ModelId("claude-sonnet-5".into()),
            system: vec![],
            tools: vec![],
            messages: vec![Message {
                role: Role::User,
                content: vec![Content::Text {
                    text: "read a.rs".into(),
                }],
            }],
            effort: Effort::High,
            max_tokens: 1024,
            thinking: Thinking::Off,
            cache_breakpoints: vec![],
            stop_sequences: vec![],
        }
    }

    /// Contract test: the wired-up `Provider::stream` client,
    /// driven against a `wiremock` server serving a real fixture byte-for-
    /// byte, must produce exactly what the pure state machine produces from
    /// the same fixture — and a `Usage` that carries the cache fields.
    #[tokio::test]
    async fn anthropic_stream_over_http() {
        let fixture = one_tool_call_fixture();

        let server = wiremock::MockServer::start().await;
        wiremock::Mock::given(wiremock::matchers::method("POST"))
            .and(wiremock::matchers::path("/v1/messages"))
            .respond_with(
                wiremock::ResponseTemplate::new(200)
                    .set_body_raw(fixture.clone(), "text/event-stream"),
            )
            .mount(&server)
            .await;

        let mut client = provider(false);
        client.base_url = server.uri();

        let (tx, mut rx) = mpsc::channel(64);
        let got_usage = client
            .stream(minimal_request(), tx, CancellationToken::new())
            .await
            .expect("stream succeeds");

        let got_events = drain_events(&mut rx).await;

        // Golden: the same fixture replayed straight through the pure state
        // machine (no network) must match exactly.
        let mut machine = stream::AnthropicStream::new();
        let mut want_events = Vec::new();
        for (event, data) in crate::sse::parse_sse_str(&fixture) {
            want_events.extend(
                machine
                    .feed(event.as_deref(), &data)
                    .expect("fixture parses"),
            );
        }

        // `ToolUseStart.id` is a freshly minted random `CallId` on every
        // `feed` call (see `stream.rs`'s module header), so the live and
        // golden runs mint different ones even for the same fixture;
        // normalize both before comparing structure.
        assert_eq!(
            stream::normalize_tool_ids(got_events),
            stream::normalize_tool_ids(want_events)
        );
        assert_eq!(got_usage.cache_read_tokens, 50);
        assert_eq!(got_usage.cache_write_tokens, 100);
        assert_eq!(got_usage.output_tokens, 24);
    }

    /// `with_key(None, …)` — the LM Studio path when "Require
    /// Authentication" is off — sends no `x-api-key` header at all. The
    /// later-mounted mock only matches when `x-api-key` *is* sent and
    /// answers 401, so the client wrongly sending it fails the test. The
    /// stream still parses the tool-call fixture end to end, proving the
    /// wire and parsing are unchanged.
    #[tokio::test]
    async fn stream_sends_no_x_api_key_header_without_a_key() {
        let fixture = one_tool_call_fixture();
        let server = wiremock::MockServer::start().await;
        wiremock::Mock::given(wiremock::matchers::method("POST"))
            .and(wiremock::matchers::path("/v1/messages"))
            .respond_with(
                wiremock::ResponseTemplate::new(200)
                    .set_body_raw(fixture.clone(), "text/event-stream"),
            )
            .mount(&server)
            .await;
        wiremock::Mock::given(wiremock::matchers::method("POST"))
            .and(wiremock::matchers::path("/v1/messages"))
            .and(wiremock::matchers::header_exists("x-api-key"))
            .respond_with(wiremock::ResponseTemplate::new(401).set_body_string("no auth wanted"))
            .mount(&server)
            .await;

        let transport = Transport {
            base_url: server.uri(),
            api_key_env: String::new(),
            timeout_s: 30,
            max_retries: 0,
        };
        let client =
            AnthropicProvider::with_key(&transport, None, CacheTtl::FiveMinutes, false, 32_768)
                .expect("builds keyless");

        let (tx, mut rx) = mpsc::channel(64);
        client
            .stream(minimal_request(), tx, CancellationToken::new())
            .await
            .expect("keyless stream succeeds");
        let events = drain_events(&mut rx).await;
        assert!(
            events
                .iter()
                .any(|e| matches!(e, ProviderEvent::ToolUseStart { .. }))
        );
    }

    /// A resolved key (LM Studio's `LM_API_TOKEN`, or Anthropic's own) is
    /// sent as `x-api-key` — the same header LM Studio's Anthropic-compatible
    /// path accepts.
    #[tokio::test]
    async fn stream_sends_x_api_key_header_with_a_key() {
        let fixture = one_tool_call_fixture();
        let server = wiremock::MockServer::start().await;
        wiremock::Mock::given(wiremock::matchers::method("POST"))
            .and(wiremock::matchers::path("/v1/messages"))
            .and(wiremock::matchers::header("x-api-key", "lm-test-token"))
            .respond_with(
                wiremock::ResponseTemplate::new(200).set_body_raw(fixture, "text/event-stream"),
            )
            .mount(&server)
            .await;

        let transport = Transport {
            base_url: server.uri(),
            api_key_env: String::new(),
            timeout_s: 30,
            max_retries: 0,
        };
        let client = AnthropicProvider::with_key(
            &transport,
            Some("lm-test-token".to_string()),
            CacheTtl::FiveMinutes,
            false,
            32_768,
        )
        .expect("builds with a key");

        let (tx, mut rx) = mpsc::channel(64);
        client
            .stream(minimal_request(), tx, CancellationToken::new())
            .await
            .expect("keyed stream succeeds");
        let events = drain_events(&mut rx).await;
        assert!(
            events
                .iter()
                .any(|e| matches!(e, ProviderEvent::ToolUseStart { .. }))
        );
    }

    /// two 429s before any byte, then a 200 — the caller sees two
    /// `Retrying` events and one clean stream.
    #[tokio::test]
    async fn retry_retries_then_succeeds() {
        use wiremock::matchers::{method, path};
        let fixture = one_tool_call_fixture();
        let server = wiremock::MockServer::start().await;
        wiremock::Mock::given(method("POST"))
            .and(path("/v1/messages"))
            .respond_with(wiremock::ResponseTemplate::new(429).insert_header("retry-after", "0"))
            .up_to_n_times(2)
            .mount(&server)
            .await;
        wiremock::Mock::given(method("POST"))
            .and(path("/v1/messages"))
            .respond_with(
                wiremock::ResponseTemplate::new(200).set_body_raw(fixture, "text/event-stream"),
            )
            .mount(&server)
            .await;
        let mut client = provider(false);
        client.base_url = server.uri();

        let (tx, mut rx) = mpsc::channel(64);
        let usage = client
            .stream(minimal_request(), tx, CancellationToken::new())
            .await
            .expect("third attempt succeeds");
        assert_eq!(usage.output_tokens, 24);
        let events = drain_events(&mut rx).await;
        let attempts: Vec<u32> = events
            .iter()
            .filter_map(|e| match e {
                ProviderEvent::Retrying { attempt, .. } => Some(*attempt),
                _ => None,
            })
            .collect();
        assert_eq!(attempts, [1, 2]);
        assert!(
            events
                .iter()
                .any(|e| matches!(e, ProviderEvent::MessageStart { .. }))
        );
        assert_eq!(server.received_requests().await.map(|r| r.len()), Some(3));
    }

    /// cancelling mid-stream drops the response body, which closes the
    /// socket — observed by a raw server as EOF within 200 ms.
    #[tokio::test]
    async fn retry_cancel_mid_stream_drops_connection() {
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("bind");
        let addr = listener.local_addr().expect("addr");
        let server = tokio::spawn(async move {
            let (mut sock, _) = listener.accept().await.expect("accept");
            let mut buf = vec![0u8; 8192];
            let _ = sock.read(&mut buf).await;
            let head = "HTTP/1.1 200 OK\r\ncontent-type: text/event-stream\r\ntransfer-encoding: chunked\r\n\r\n";
            let frame = "event: message_start\ndata: {\"type\":\"message_start\",\"message\":{\"id\":\"m\",\"type\":\"message\",\"role\":\"assistant\",\"model\":\"claude-sonnet-5\",\"content\":[],\"stop_reason\":null,\"usage\":{\"input_tokens\":1,\"output_tokens\":1}}}\n\n";
            let chunk = format!("{head}{:x}\r\n{frame}\r\n", frame.len());
            sock.write_all(chunk.as_bytes()).await.expect("write");
            // Keep the stream open; the client's close is the only way out.
            loop {
                match sock.read(&mut buf).await {
                    Ok(0) | Err(_) => return std::time::Instant::now(),
                    Ok(_) => {}
                }
            }
        });
        let mut client = provider(false);
        client.base_url = format!("http://{addr}");
        let cancel = CancellationToken::new();
        let (tx, mut rx) = mpsc::channel(64);
        let streaming = {
            let cancel = cancel.clone();
            tokio::spawn(async move { client.stream(minimal_request(), tx, cancel).await })
        };
        let first = tokio::time::timeout(std::time::Duration::from_secs(5), rx.recv())
            .await
            .expect("first event in time");
        assert!(matches!(first, Some(ProviderEvent::MessageStart { .. })));
        let cancelled_at = std::time::Instant::now();
        cancel.cancel();
        assert!(matches!(
            streaming.await.expect("join"),
            Err(ProviderError::Cancelled)
        ));
        let closed_at = tokio::time::timeout(std::time::Duration::from_secs(2), server)
            .await
            .expect("server saw the close")
            .expect("server task");
        assert!(closed_at.duration_since(cancelled_at) < std::time::Duration::from_millis(200));
    }
}
