//! The Anthropic Messages API backend: request translation, the SSE stream
//! parser and a streaming client.
//!
//! Kept apart from the OpenAI backends because the fields that decide cost
//! here — `cache_control` placement, `output_config.effort`, adaptive
//! `thinking`, `fallbacks` — have no counterpart there.
//!
//! The wire types are generated by `build.rs` with typify from the vendored
//! spec in `schema/`; they stay private, the other modules are their only
//! consumers.

pub mod request;
/// Wire types generated from the vendored OpenAPI spec — internal to this
/// module; `request` and `stream` are the only consumers.
mod wire;

/// How long a cache entry written by a `cache_control` breakpoint lives.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum CacheTtl {
    /// The API default.
    #[default]
    FiveMinutes,
    /// Longer TTL for bursty sessions; writes cost more.
    OneHour,
}

impl CacheTtl {
    /// The wire value for `cache_control.ttl`.
    pub fn as_str(self) -> &'static str {
        match self {
            CacheTtl::FiveMinutes => "5m",
            CacheTtl::OneHour => "1h",
        }
    }
}
