/* Generated by cbindgen from tests/fixtures/ffi/src: ABI_DRIFT_BLESS=1 cargo test -p abi-drift. Do not edit. */

#ifndef FFI_H
#define FFI_H



#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A point in the fixture's ABI.
 */
typedef struct FfiPoint {
  int32_t x;
  int32_t y;
} FfiPoint;

/**
 * Adds two numbers.
 */
int32_t ffi_add(int32_t a, int32_t b);

/**
 * The origin.
 */
struct FfiPoint ffi_origin(void);

#endif  /* FFI_H */
